---

- hosts: all

  become: true

  gather_facts: false

  vars_files:
    - params/repos_sle.yml

  tasks:

    - name: 'Add repositories for SLE 15 SP2'
      include_role:
        name: add_repos_SUSE

- hosts: all

  become: true

  gather_facts: false

  vars_files:
    - params/repos_ses.yml

  tasks:

    - name: 'Add repositories for SES 7'
      include_role:
        name: add_repos_SUSE

- hosts: all

  become: true

  gather_facts: false

  roles:
    - refresh_update_SUSE
    - reboot_SUSE

  tasks:

    - name: 'Install relevant SUSE products'
      zypper:
        name: [SLES,
               sle-module-basesystem,
               sle-module-server-applications,
               ses]
        type: product
        state: present
        update_cache: true

    - name: 'Check whether service firewalld is present'
      shell: |
        set -o pipefail
        systemctl list-unit-files --no-pager | grep firewalld || /bin/true
      register: service_list
      changed_when: false

    - name: 'Stop and disable service firewalld'
      service:
        name: firewalld
        state: stopped
        enabled: false
      when: '"firewalld.service" in service_list.stdout'

    - name: 'Install packages ca-certificates-suse, chrony'
      zypper:
        name: [ca-certificates-suse, chrony]
        state: present
        update_cache: true

    - name: 'Start and enable service chronyd'
      service:
        name: chronyd
        state: started
        enabled: true
