---

- hosts: all

  become: true

  gather_facts: false

  vars_files:
    - repos_ses.yml

  tasks:

    - name: 'Remove SES 7 repositories'
      include_role:
        name: remove_repos_SUSE

- hosts: all

  become: true

  gather_facts: false

  vars_files:
    - repos_ses_new.yml

  tasks:

    - name: 'Add repositories for SES 7 Pacific'
      include_role:
        name: add_repos_SUSE

- hosts: all

  become: true

  gather_facts: false

  roles:
    - refresh_update_SUSE
    - reboot_SUSE

- hosts: admin

  become: true

  gather_facts: false

  tasks:

    - name: 'Take a breather'
      pause:
        seconds: 15

    - name: 'Specify the openSUSE container registry, for downloading Pacific images'
      shell: ceph-salt config /cephadm_bootstrap/ceph_image_path set registry.opensuse.org/filesystems/ceph/pacific/images/ceph/ceph
      changed_when: false

    - name: 'Initiate the container upgrade process'
      shell: ceph orch upgrade start --image registry.opensuse.org/filesystems/ceph/pacific/images/ceph/ceph:latest
      changed_when: false

    - name: 'Tip'
      debug:
        msg: "Type 'ceph -W cephadm' to watch how the upgrade progresses"

    - name: 'Tip'
      debug:
        msg: "Type 'ceph versions' after the upgrade completes"
