---

- hosts: all

  become: true

  gather_facts: false

  vars_files:
    - repos_sle.yml

  tasks:

    - name: 'Remove SLE 15 SP2 repositories'
      include_role:
        name: remove_repos_SUSE

- hosts: all

  become: true

  gather_facts: false

  vars_files:
    - repos_sle_new.yml

  tasks:

    - name: 'Add repositories for SLE 15 SP3'
      include_role:
        name: add_repos_SUSE

- hosts: all

  become: true

  gather_facts: false

  tasks:

    - name: 'Perform distribution upgrade (this may take a while)'
      shell: zypper --non-interactive dist-upgrade --download-in-advance --allow-vendor-change warn=no
      changed_when: false

    - name: 'Get name and version of the OS we are running on'
      shell: |
        . /etc/os-release
        echo $PRETTY_NAME
      register: pretty_name
      changed_when: false

    - name: "'. /etc/os-release ; echo $PRETTY_NAME' output"
      debug:
        msg: 'Running on {{ pretty_name.stdout }}'

- hosts: all

  become: true

  gather_facts: false

  tasks:

    - name: 'Reboot system'
      include_role:
        name: reboot_SUSE
